Style/Documentation:
  Description: "Document classes and non-namespace modules."
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false