default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_bin
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV["DATABASE_HOSTNAME"] %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>

development:
  <<: *default
  database: crawler_bot_development

test:
  <<: *default
  database: crawler_bot_test

production:
  <<: *default
  url: <%= ENV.fetch('JAWSDB_URL', '').sub('mysql://', 'mysql2://') %>